import {
  BadgeCheck,
  Bot,
  FileText,
  Landmark,
  Shield,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

const scoreCards = [
  {
    icon: TrendingUp,
    title: "Financial Health Score",
    description:
      "Measures overall wallet strength using income consistency, savings patterns and spending behavior.",
  },
  {
    icon: Shield,
    title: "Reputation Score",
    description:
      "Evaluates wallet maturity, transaction history and long-term financial reliability.",
  },
  {
    icon: BadgeCheck,
    title: "Income Stability",
    description:
      "Detects recurring income streams and estimates income consistency over time.",
  },
  {
    icon: Landmark,
    title: "Loan Capacity Estimate",
    description:
      "Suggests a responsible borrowing range based on observed wallet activity.",
  },
];

const bottomCards = [
  {
    icon: FileText,
    title: "Transaction Statements",
    description: "Generate wallet transaction statements for:",
    periods: ["Last 3 Months", "Last 6 Months", "Last 12 Months"],
    emphasized: true,
  },
  {
    icon: Bot,
    title: "AI Financial Summary",
    description:
      "A lender-friendly explanation of the wallet's financial behavior generated by OnFRA.",
    emphasized: false,
  },
];

type ReportCardProps = {
  icon: LucideIcon;
  title: string;
  description: string;
  periods?: string[];
  emphasized?: boolean;
};

function ReportCard({
  icon: Icon,
  title,
  description,
  periods,
  emphasized,
}: ReportCardProps) {
  return (
    <div
      className={`group relative rounded-2xl border p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_0_30px_-10px_rgba(247,147,26,0.2)] ${
        emphasized
          ? "border-btc-gold/40 bg-btc-gold/5 hover:border-btc-gold/60"
          : "border-white/10 bg-void-surface hover:border-btc-orange/50"
      }`}
    >
      {emphasized && (
        <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-btc-gold/60 to-transparent" />
      )}
      <div
        className={`mb-4 grid h-10 w-10 place-items-center rounded-lg border text-btc-orange ${
          emphasized
            ? "border-btc-gold/50 bg-btc-gold/20"
            : "border-btc-burnt/50 bg-btc-burnt/20"
        }`}
      >
        <Icon size={18} />
      </div>
      <h3 className="font-space text-base font-semibold text-white">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-stardust">{description}</p>
      {periods && (
        <ul className="mt-4 grid gap-2 border-t border-white/10 pt-4 sm:grid-cols-3">
          {periods.map((period) => (
            <li
              key={period}
              className="flex items-center gap-2 font-mono text-xs text-btc-gold"
            >
              <span className="text-btc-orange">•</span>
              {period}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export function ReportContentsSection() {
  return (
    <section
      id="report-contents"
      className="border-t border-white/10 bg-black px-6 py-24"
    >
      <div className="mx-auto max-w-7xl">
        <p className="text-center font-mono text-[10px] uppercase tracking-widest text-btc-orange">
          What&apos;s Inside Your Report
        </p>
        <h2 className="mt-3 text-center font-space text-3xl font-bold text-white md:text-4xl">
          Everything lenders need to evaluate you
        </h2>

        <div className="mt-14 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {scoreCards.map((item) => (
            <ReportCard key={item.title} {...item} />
          ))}
        </div>

        <div className="mt-5 grid grid-cols-1 gap-5 md:grid-cols-2">
          {bottomCards.map((item) => (
            <ReportCard key={item.title} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
}
