import { tool } from "@langchain/core/tools";
import { z } from "zod";
import crypto from "crypto";

export const reportCompiler = tool(
  async ({
    walletAddress,
    onchainDataJson,
    financialHealthJson,
    reputationJson,
    riskExposureJson,
    incomeStabilityJson,
    loanCapacityJson,
    aiSummary,
  }) => {
    const rawData = JSON.parse(onchainDataJson);
    const healthData = JSON.parse(financialHealthJson);
    const repData = JSON.parse(reputationJson);
    const riskData = JSON.parse(riskExposureJson);
    const incomeData = JSON.parse(incomeStabilityJson);
    const loanData = JSON.parse(loanCapacityJson);

    const timestamp = new Date().toISOString();
    const alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const suffix = Array.from(crypto.randomBytes(10))
      .map((byte) => alphabet[byte % alphabet.length])
      .join("");
    const reportId = `REP-${suffix}`;

    // Compile into sections
    const report = {
      reportId,
      timestamp,
      identity: {
        walletAddress,
        ens: rawData.ens || "None",
        activeChains: ["Ethereum Mainnet", "Arbitrum", "Polygon"], // mock list
        walletAgeMonths: rawData.walletAgeMonths,
      },
      threeMonthStatement: rawData.threeMonthStatement || {
        totalInflowUsd: 0,
        totalOutflowUsd: 0,
        netFlowUsd: 0,
        transactionCount: 0
      },
      financialSummary: {
        totalInflow: incomeData.averageInflowSizeUsd * rawData.transactions.filter((t: any) => t.type === "inflow").length,
        totalOutflow: rawData.transactions.filter((t: any) => t.type === "outflow").reduce((sum: number, t: any) => sum + t.amountUsd, 0),
        averageMonthlyInflow: incomeData.monthlyIncomeEstimateUsd,
        stablecoinHoldings: rawData.stablecoinBalance,
        activeProtocolsCount: rawData.protocols.length,
        portfolioValue: rawData.stablecoinBalance + rawData.volatileBalance,
      },
      financialHealth: {
        financialHealthScore: healthData.financialHealthScore,
        reputationScore: repData.reputationScore,
        riskCategory: riskData.riskCategory,
        stabilityScore: healthData.breakdown.incomeStability,
        subScores: healthData.breakdown,
      },
      incomeAnalysis: {
        recurringInflows: incomeData.recurringSenderPatterns,
        estimatedMonthlyEarnings: incomeData.monthlyIncomeEstimateUsd,
        consistencyAnalysis: `${incomeData.weeklyInflowConsistency}% weekly inflow consistency`,
        funLabel: incomeData.incomeLabel,
      },
      loanSuitability: {
        estimatedSafeBorrowingCapacity: loanData.safeLoanRange,
        confidenceLevel: loanData.confidence,
      },
      riskAssessment: {
        volatilityExposure: `${riskData.breakdown.volatileAssetPct}% volatile assets`,
        defiExposure: `${riskData.breakdown.defiExposurePct}% DeFi allocations`,
        suspiciousDrains: rawData.walletAddress.toLowerCase().includes("bad") ? "High (Flagged Interactions)" : "None",
      },
      aiSummary: aiSummary || "Analysis in progress.",
      verification: {
        erc804AgentIdentity: "0x804ScoreAgentContractAddressPlaceHolder",
        verificationEndpoint: `${process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") || "https://app.onfra.xyz"}/api/agent/verify/${reportId}`,
        reportHash: "",
      },
    };

    // Calculate report hash (excluding hash field)
    const reportString = JSON.stringify(report);
    const hash = crypto.createHash("sha256").update(reportString).digest("hex");
    report.verification.reportHash = `0x${hash}`;

    return JSON.stringify(report, null, 2);
  },
  {
    name: "report_compiler",
    description: "Compiles all financial metrics and AI summary into a unified structured report JSON. Returns complete report representation.",
    schema: z.object({
      walletAddress: z.string().describe("The wallet address analyzed"),
      onchainDataJson: z.string().describe("JSON output from fetch_onchain_data"),
      financialHealthJson: z.string().describe("JSON output from compute_financial_health"),
      reputationJson: z.string().describe("JSON output from compute_reputation_score"),
      riskExposureJson: z.string().describe("JSON output from risk_exposure_breakdown"),
      incomeStabilityJson: z.string().describe("JSON output from income_stability_analysis"),
      loanCapacityJson: z.string().describe("JSON output from loan_capacity_estimator"),
      aiSummary: z.string().optional().describe("AI Summary generated by LLM"),
    }),
  }
);
